const fs = require("fs");
const path = require("path");
const program = require("commander");

const runBuild = require("./build/runBuild");
const runServer = require("./build/runServer");

const DEFAULT_PORT = 8080;

const packageInfo = require("./package.json");

function main() {
  const cwd = process.cwd();

  program
    .name(packageInfo.name.replace("@tototoshi/", ""))
    .version(packageInfo.version)
    .option("-o, --out <out>", "Specify where to generate the file", "dist")
    .option(
      "-p, --port <port>",
      "The port the server will listen on",
      DEFAULT_PORT
    )
    .option("-w, --write", "Write files generated by the dev server")
    .option("-s, --serve", "Run the dev server")
    .option(
      "-t, --theme <theme>",
      "Specify the name of theme <default|dark|blue>",
      "default"
    )
    .arguments("<filename>")
    .parse(process.argv);
  const options = program.opts();
  const port = parseInt(options.port);
  const outputPath = path.resolve(cwd, options.out);
  const write = options.write || false;
  const serve = options.serve || false;
  const theme = options.theme;

  if (program.args.length === 1) {
    const filename = path.resolve(cwd, program.args[0]);

    if (!fs.existsSync(filename)) {
      console.error(`${filename} does not exist`);
      process.exit(1);
    }

    if (serve) {
      runServer(cwd, outputPath, port, filename, write, theme);
    } else {
      runBuild(cwd, outputPath, filename, theme);
    }
  } else {
    program.help();
  }
}

main();
